import { getPool } from './db';

let _ensured = false;

export async function ensureFerrTables(): Promise<void> {
  if (_ensured) return;

  const pool = await getPool();

  await Promise.all([
    pool.request().query(`
      IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TI-PAINELCOMISSAO_FERRAGENS_METAS')
      CREATE TABLE [TI-PAINELCOMISSAO_FERRAGENS_METAS] (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        VENDEDOR VARCHAR(150) NOT NULL,
        ANO INT NOT NULL,
        MES INT NOT NULL,
        META1_VALOR FLOAT DEFAULT 0,
        META1_PERCENTUAL FLOAT DEFAULT 0,
        META2_VALOR FLOAT DEFAULT 0,
        META2_PERCENTUAL FLOAT DEFAULT 0,
        META3_VALOR FLOAT DEFAULT 0,
        META3_PERCENTUAL FLOAT DEFAULT 0,
        METADESAFIO_VALOR FLOAT DEFAULT 0,
        METADESAFIO_PERCENTUAL FLOAT DEFAULT 0,
        PERCENTUAL_SEM_META FLOAT DEFAULT 0
      )
    `),
    pool.request().query(`
      IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TI-PAINELCOMISSAO_FERRAGENS_BONUS')
      CREATE TABLE [TI-PAINELCOMISSAO_FERRAGENS_BONUS] (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        VENDEDOR VARCHAR(150) NOT NULL,
        ANO INT NOT NULL,
        MES INT NOT NULL,
        BONUS1_VALOR FLOAT DEFAULT 0,
        BONUS2_VALOR FLOAT DEFAULT 0,
        BONUS3_VALOR FLOAT DEFAULT 0,
        BONUSDESAFIO_VALOR FLOAT DEFAULT 0
      )
    `),
    pool.request().query(`
      IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TI-PAINELCOMISSAO_FERRAGENS_META_GRUPO')
      CREATE TABLE [TI-PAINELCOMISSAO_FERRAGENS_META_GRUPO] (
        ID INT IDENTITY(1,1) PRIMARY KEY,
        ANO INT NOT NULL,
        MES INT NOT NULL,
        META1_VALOR FLOAT DEFAULT 0, META1_BONUS FLOAT DEFAULT 0,
        META2_VALOR FLOAT DEFAULT 0, META2_BONUS FLOAT DEFAULT 0,
        META3_VALOR FLOAT DEFAULT 0, META3_BONUS FLOAT DEFAULT 0,
        METADESAFIO_VALOR FLOAT DEFAULT 0, METADESAFIO_BONUS FLOAT DEFAULT 0
      )
    `),
  ]);

  _ensured = true;
}
